@startuml
title Saque Bancário

[*] --> AguardandoCartao
state "Aguardando Cartao" as AguardandoCartao
state "Cartão Inserido" as CartaoInserido
state "Aguardando Senha" as AguardandoSenha
state "Verificando Senha" as VerificandoSenha
state "Saque Autorizado" as SaqueAutorizado
state "Saque Recusado" as SaqueRecusado
state "Liberando o Dinheiro" as LiberandoDinheiro
state "Devolvendo cartão" as DevolvendoCartao
state "Operação Concluida" as OperacaoConcluida
state "Operação cancelada" as OperacaoCancelada
 
state EscolhaSenha <<choice>>
state EscolhaSaldo <<choice>>

AguardandoCartao --> CartaoInserido : inserir Cartão
CartaoInserido --> AguardandoSenha: Solicitar Senha
AguardandoSenha --> VerificandoSenha: informar Senha
VerificandoSenha --> EscolhaSenha
EscolhaSenha --> AguardandoValor: [Senha correta]
EscolhaSenha --> SenhaIncorreta : [Senha incorreta]
SenhaIncorreta --> AguardandoSenha: tentar
SenhaIncorreta --> OperacaoCancelada :

@enduml